### ISSUE TITLE
[Bug report] - On specific eid : No data loading when launching TaskQC

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#46] opened 2020-09-18 11:49 UTC
**Describe the bug**
From ibllib master branch, I am trying to launch this:

```
from ibllib.qc.task_metrics import TaskQC
from ibllib.qc.qcplots import plot_results
eid = '695a6073-eae0-49e0-bb0f-e9e57a9275b9'
qc = TaskQC(eid)

```
it runs, but `qc` is basically empty. As a result, the plotting fails.

The QC seems to have run fine previously as per Alyx: https://alyx.internationalbrainlab.org/admin/actions/ephyssession/695a6073-eae0-49e0-bb0f-e9e57a9275b9/change/ 

**To Reproduce**
Code above.

**Expected behavior**
Plots.

**Comment by mayofaulkner** [comment] 2020-09-23 12:27
Duplicate of issue #50 .

Calling any of the run, load_data and compute methods will load the data. Example: qc.run().

**Closed by mayofaulkner** 2020-09-23 12:27 UTC
Labels: bug
