### ISSUE TITLE
[Usage question] - How to go from session to tasks using one rest query 

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#107] opened 2020-11-12 12:51 UTC
**Describe the question you have**
Using ONE, I would like to search for sessions which do (or don't) have extraction tasks errored.

I know how to look for tasks which errored, and could find the sessions eid based on this:
```
tasks_error = one.alyx.rest('tasks', 'list',
                            django='status,40,'
                                   'session__task_protocol__icontains,ephys')
```

However what would be more practical, is to have a Django query to filter sessions based on their task status.
Is it possible to go from session to tasks ? something like:
```
sessions_error = one.alyx.rest('sessions', 'list', task_protocol='ephys',
                            django='[xxx]__task__status,40')
```
I am missing the `[xxx]` part here, I do not see how to get there from the current list of filters listed on https://alyx.internationalbrainlab.org/docs/#sessions-list

**Is your question related to a specific product?**
Alyx, ONE

**Comment by GaelleChapuis** [comment] 2020-11-12 12:56
[maybe it makes more sense to go from the probe trajectory or insertion, but the question remains the same]

**Comment by oliche** [comment] 2020-11-19 09:09
cf. documentation here for advanced related fields queries: https://alyx.internationalbrainlab.org/admin/doc/models/actions.session/
In this case we want the tasks related, do the query will be like

`sessions_error = one.alyx.rest('sessions', 'list', task_protocol='ephys', django='tasks__status,40')`


Another option is to hit the task endpoint and get eids from there
```
tasks = one.alyx.rest('tasks', 'list', name="SpikeSorting_KS2_Matlab", status="Errored")
[t['session'] for t in tasks]
```

Closing this for now...

**Comment by GaelleChapuis** [comment] 2020-11-23 17:20
How do you do to get the sessions for which a specific task failed?

e.g. 
`sessions_error = one.alyx.rest('sessions', 'list', task_protocol='ephys', django='tasks__status,40 AND tasks__name,SpikeSorting_KS2_Matlab')`

**Closed** 2020-11-24 16:26 UTC
Labels: question

**Comment by GaelleChapuis** [comment] 2020-11-24 16:49
if you do
```
sessions_error = one.alyx.rest('sessions', 'list', task_protocol='ephys', django='tasks__status,40,tasks__name,SpikeSorting_KS2_Matlab')
```
you get 300 sessions

whilst if you do
```
tasks = one.alyx.rest('tasks', 'list', name="SpikeSorting_KS2_Matlab", status="Errored")
s_e = [t['session'] for t in tasks]
```
you get 71 sessions.

I was expecting those 2 numbers to match, hence my question (I know a comma is equivalent to AND but in this case it does not seem to work as intended).
But it's alright, I'll figure it out, keeping the issue as closed is fine.

**Comment by oliche** [comment] 2020-11-24 18:01
Well, everything work as intended, but  it's not a stupid question either as it's a subtle case.

Directly in the model  the query means "give me tasks with status 40 and name ks2".
On a related field the query means "give me sessions with task status 40 and the sessions with task name ks2". It's an AND on the sessions, but is equivalent to an OR on the related field !

In this case if you need the sessions dict: 

```
tasks = one.alyx.rest('tasks', 'list', name="SpikeSorting_KS2_Matlab", status="Errored")
s_e = [t['session'] for t in tasks]
sessions_error = one.alyx.rest('sessions', 'list', django=f'pk__in,{s_e}')
```
(not sure how scalable it is, I'm not sure feeding thousands of eid through an URL would work but in this case it's ok).
